### ISSUE TITLE
e2e test failing with missing dart file

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/js_facade_gen#2]
```console
> gulp test.e2e
[16:54:52] Using gulpfile ~/source/github/js_facade_gen/gulpfile.js
[16:54:52] Starting 'compile'...
[16:54:53] Finished 'compile' after 1.62 s
[16:54:53] Starting 'test.compile'...
[16:54:54] Finished 'test.compile' after 795 ms
[16:54:54] Starting 'test.e2e'...
Transpiling [] to .
Resolving dependencies...
Package test has no versions that match 0.12.13 derived from:
- e2e depends on version 0.12.13
Unhandled exception:
Could not load "file:///Users/kevmoo/source/github/js_facade_gen/build/e2e/helloworld.dart": FileSystemException: Cannot open file, path = '/Users/kevmoo/source/github/js_facade_gen/build/e2e/helloworld.dart' (OS Error: No such file or directory, errno = 2)
null
[16:54:56] 'test.e2e' errored after 1.88 s
[16:54:56] Error: 255
    at formatError (/Users/kevmoo/homebrew/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/kevmoo/homebrew/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/kevmoo/source/github/js_facade_gen/node_modules/orchestrator/index.js:264:8)
    at /Users/kevmoo/source/github/js_facade_gen/node_modules/orchestrator/index.js:275:23
    at finish (/Users/kevmoo/source/github/js_facade_gen/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/Users/kevmoo/source/github/js_facade_gen/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
```

**Comment by jacob314** [comment]
The e2e test wasn't adding value. Removed.
