### ISSUE TITLE
Enum type not supported

### ISSUE THREAD

**Issue by sestegra** [dart-lang/js_facade_gen#86]
When using `dart_js_facade_gen` version 0.0.7 on google-app-scripts definition files, I got following errors

```
$ dart_js_facade_gen google-apps-script.utilities.d.ts
/usr/local/lib/node_modules/dart_js_facade_gen/index.js:28
  if (e.name !== 'DartFacadeError') throw e;
                                    ^

TypeError: Cannot read property 'getSourceFile' of undefined
    at Transpiler.reportError (/usr/local/lib/node_modules/dart_js_facade_gen/build/lib/main.js:407:22)
    at FacadeConverter.reportError (/usr/local/lib/node_modules/dart_js_facade_gen/build/lib/base.js:395:25)
    at FacadeConverter.getTypeDeclarationOfSymbol (/usr/local/lib/node_modules/dart_js_facade_gen/build/lib/facade_converter.js:615:18)
    at MergedType.merge (/usr/local/lib/node_modules/dart_js_facade_gen/build/lib/merge.js:39:42)
    at MergedParameter.merge (/usr/local/lib/node_modules/dart_js_facade_gen/build/lib/merge.js:112:19)
    at new MergedParameter (/usr/local/lib/node_modules/dart_js_facade_gen/build/lib/merge.js:105:14)
    at /usr/local/lib/node_modules/dart_js_facade_gen/build/lib/declaration.js:417:33
    at Array.forEach (<anonymous>)
    at DeclarationTranspiler.visitMergingOverloads (/usr/local/lib/node_modules/dart_js_facade_gen/build/lib/declaration.js:346:23)
    at DeclarationTranspiler.visitClassBody (/usr/local/lib/node_modules/dart_js_facade_gen/build/lib/declaration.js:236:14)
```

```
$ dart_js_facade_gen google-apps-script.calendar.d.ts
google-apps-script.calendar.d.ts:135:22: no type declarations for symbol GuestStatus
google-apps-script.calendar.d.ts:142:24: no type declarations for symbol Visibility
google-apps-script.calendar.d.ts:161:27: no type declarations for symbol GuestStatus
google-apps-script.calendar.d.ts:165:33: no type declarations for symbol Visibility
google-apps-script.calendar.d.ts:190:22: no type declarations for symbol GuestStatus
google-apps-script.calendar.d.ts:196:24: no type declarations for symbol Visibility
google-apps-script.calendar.d.ts:211:27: no type declarations for symbol GuestStatus
google-apps-script.calendar.d.ts:216:33: no type declarations for symbol Visibility
google-apps-script.calendar.d.ts:232:25: no type declarations for symbol GuestStatus
```

**Comment by iampawan** [comment]
Did you find any workaround?
